# Generated by Django 3.2 on 2021-04-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210407_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('date_added',)},
        ),
    ]
